/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package kafka.producer.location.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BdaAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -798399645075620289L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Bda\",\"namespace\":\"kafka.producer.location.schema\",\"fields\":[{\"name\":\"alternateCodes\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AlternateCode\",\"fields\":[{\"name\":\"code\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"codeType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}}},{\"name\":\"bdaType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BdaAvro> ENCODER =
      new BinaryMessageEncoder<BdaAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BdaAvro> DECODER =
      new BinaryMessageDecoder<BdaAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BdaAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BdaAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BdaAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BdaAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Bda to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Bda from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Bda instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BdaAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.List<AlternateCodeAvro> alternateCodes;
  private java.lang.String bdaType;
  private java.lang.String name;
  private java.lang.String type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BdaAvro() {}

  /**
   * All-args constructor.
   * @param alternateCodes The new value for alternateCodes
   * @param bdaType The new value for bdaType
   * @param name The new value for name
   * @param type The new value for type
   */
  public BdaAvro(java.util.List<AlternateCodeAvro> alternateCodes, java.lang.String bdaType, java.lang.String name, java.lang.String type) {
    this.alternateCodes = alternateCodes;
    this.bdaType = bdaType;
    this.name = name;
    this.type = type;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return alternateCodes;
    case 1: return bdaType;
    case 2: return name;
    case 3: return type;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: alternateCodes = (java.util.List<AlternateCodeAvro>)value$; break;
    case 1: bdaType = value$ != null ? value$.toString() : null; break;
    case 2: name = value$ != null ? value$.toString() : null; break;
    case 3: type = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'alternateCodes' field.
   * @return The value of the 'alternateCodes' field.
   */
  public java.util.List<AlternateCodeAvro> getAlternateCodes() {
    return alternateCodes;
  }


  /**
   * Sets the value of the 'alternateCodes' field.
   * @param value the value to set.
   */
  public void setAlternateCodes(java.util.List<AlternateCodeAvro> value) {
    this.alternateCodes = value;
  }

  /**
   * Gets the value of the 'bdaType' field.
   * @return The value of the 'bdaType' field.
   */
  public java.lang.String getBdaType() {
    return bdaType;
  }


  /**
   * Sets the value of the 'bdaType' field.
   * @param value the value to set.
   */
  public void setBdaType(java.lang.String value) {
    this.bdaType = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.String getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.String value) {
    this.type = value;
  }

  /**
   * Creates a new Bda RecordBuilder.
   * @return A new Bda RecordBuilder
   */
  public static BdaAvro.Builder newBuilder() {
    return new BdaAvro.Builder();
  }

  /**
   * Creates a new Bda RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Bda RecordBuilder
   */
  public static BdaAvro.Builder newBuilder(BdaAvro.Builder other) {
    if (other == null) {
      return new BdaAvro.Builder();
    } else {
      return new BdaAvro.Builder(other);
    }
  }

  /**
   * Creates a new Bda RecordBuilder by copying an existing Bda instance.
   * @param other The existing instance to copy.
   * @return A new Bda RecordBuilder
   */
  public static BdaAvro.Builder newBuilder(BdaAvro other) {
    if (other == null) {
      return new BdaAvro.Builder();
    } else {
      return new BdaAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for Bda instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BdaAvro>
    implements org.apache.avro.data.RecordBuilder<BdaAvro> {

    private java.util.List<AlternateCodeAvro> alternateCodes;
    private java.lang.String bdaType;
    private java.lang.String name;
    private java.lang.String type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(BdaAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.alternateCodes)) {
        this.alternateCodes = data().deepCopy(fields()[0].schema(), other.alternateCodes);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.bdaType)) {
        this.bdaType = data().deepCopy(fields()[1].schema(), other.bdaType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Bda instance
     * @param other The existing instance to copy.
     */
    private Builder(BdaAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.alternateCodes)) {
        this.alternateCodes = data().deepCopy(fields()[0].schema(), other.alternateCodes);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bdaType)) {
        this.bdaType = data().deepCopy(fields()[1].schema(), other.bdaType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.type)) {
        this.type = data().deepCopy(fields()[3].schema(), other.type);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'alternateCodes' field.
      * @return The value.
      */
    public java.util.List<AlternateCodeAvro> getAlternateCodes() {
      return alternateCodes;
    }


    /**
      * Sets the value of the 'alternateCodes' field.
      * @param value The value of 'alternateCodes'.
      * @return This builder.
      */
    public BdaAvro.Builder setAlternateCodes(java.util.List<AlternateCodeAvro> value) {
      validate(fields()[0], value);
      this.alternateCodes = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'alternateCodes' field has been set.
      * @return True if the 'alternateCodes' field has been set, false otherwise.
      */
    public boolean hasAlternateCodes() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'alternateCodes' field.
      * @return This builder.
      */
    public BdaAvro.Builder clearAlternateCodes() {
      alternateCodes = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'bdaType' field.
      * @return The value.
      */
    public java.lang.String getBdaType() {
      return bdaType;
    }


    /**
      * Sets the value of the 'bdaType' field.
      * @param value The value of 'bdaType'.
      * @return This builder.
      */
    public BdaAvro.Builder setBdaType(java.lang.String value) {
      validate(fields()[1], value);
      this.bdaType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'bdaType' field has been set.
      * @return True if the 'bdaType' field has been set, false otherwise.
      */
    public boolean hasBdaType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'bdaType' field.
      * @return This builder.
      */
    public BdaAvro.Builder clearBdaType() {
      bdaType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public BdaAvro.Builder setName(java.lang.String value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public BdaAvro.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.String getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public BdaAvro.Builder setType(java.lang.String value) {
      validate(fields()[3], value);
      this.type = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public BdaAvro.Builder clearType() {
      type = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BdaAvro build() {
      try {
        BdaAvro record = new BdaAvro();
        record.alternateCodes = fieldSetFlags()[0] ? this.alternateCodes : (java.util.List<AlternateCodeAvro>) defaultValue(fields()[0]);
        record.bdaType = fieldSetFlags()[1] ? this.bdaType : (java.lang.String) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.String) defaultValue(fields()[2]);
        record.type = fieldSetFlags()[3] ? this.type : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BdaAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<BdaAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BdaAvro>
    READER$ = (org.apache.avro.io.DatumReader<BdaAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.alternateCodes.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (AlternateCodeAvro e0: this.alternateCodes) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeString(this.bdaType);

    out.writeString(this.name);

    out.writeString(this.type);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<AlternateCodeAvro> a0 = this.alternateCodes;
      if (a0 == null) {
        a0 = new SpecificData.Array<AlternateCodeAvro>((int)size0, SCHEMA$.getField("alternateCodes").schema());
        this.alternateCodes = a0;
      } else a0.clear();
      SpecificData.Array<AlternateCodeAvro> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<AlternateCodeAvro>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          AlternateCodeAvro e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new AlternateCodeAvro();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

      this.bdaType = in.readString();

      this.name = in.readString();

      this.type = in.readString();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<AlternateCodeAvro> a0 = this.alternateCodes;
          if (a0 == null) {
            a0 = new SpecificData.Array<AlternateCodeAvro>((int)size0, SCHEMA$.getField("alternateCodes").schema());
            this.alternateCodes = a0;
          } else a0.clear();
          SpecificData.Array<AlternateCodeAvro> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<AlternateCodeAvro>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              AlternateCodeAvro e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new AlternateCodeAvro();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        case 1:
          this.bdaType = in.readString();
          break;

        case 2:
          this.name = in.readString();
          break;

        case 3:
          this.type = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










